### ISSUE TITLE
Boolean data type

### ISSUE THREAD

**Issue by dmw1632** [USDA/data-standards#5]
Some Boolean have Y or N and some Boolean have true and false.  For example [Precision Agricultural Sub Meter Accuracy Indicator](https://usda.github.io/data-standards/data-elements/Precision_Agricultural_Sub_Meter_Accuracy_Indicator.html)  has Y as example

**Comment by bbrotsos** [comment]
This commit https://github.com/USDA/data-standards/commit/461e0190fa71a0a89e9a8732c214ec41a5f857de closes this issue.
