### ISSUE TITLE
cluIdentifier (description, type, minLength and maxLength) copied from farmNumber

### ISSUE THREAD

**Issue by MyAgData** [USDA/data-standards#6]
In the documents [field.json](https://github.com/USDA/data-standards/blob/gh-pages/json-schema/field.json) and [all-elements.json](https://github.com/USDA/data-standards/blob/gh-pages/json-schema/all_elements.json), the cluIdentifier data type, minLength and maxLength do not match the Exchange Content Model, and the description is identical to that of fieldNumber. [This](https://usda.github.io/data-standards/data-elements/CLU_Identifier.html) page gives the following description:

> A system-generated internal identifier of a common land unit (CLU). This identifier is for internal access use only. A CLU is the smallest unit of land that has a permanent, contiguous boundary, common land cover and land management, a common owner, and a common producer association. A CLU is closely related to FSA''s definition of 'fields', according to Handbook 2-CP. A CLU is also closely related to land units such as parcels, farmsteads, and lots that are used by NRCS, RMA and RD. The authoritative source of CLU Identifier is Farm Records. CLU Identifier can remain constant even if the precise geospatial shape of the CLU is slightly altered.

The Exchange Content Model suggests type = "string" with minLength = maxLength = 36, the same as the previous standard.

**Comment by bbrotsos** [comment]
Thanks for the feedback, we'll make the update in the next update in the next couple of days.

**Comment by bbrotsos** [comment]
This commit closes this issue https://github.com/USDA/data-standards/commit/458ea0996aae328a485ab281580736890201b773  

The all-elements.json file was initially used to generate the json schemas.  It is no longer needed and has been removed.
